### ISSUE TITLE
Create image samples for Noisy pixel values 

### ISSUE THREAD

**Issue by rahulkrishnan98** [rahulkrishnan98/Numpy-array-to-Images#3]
The same procedure as used for shifted movies have to be replicated. Dimension of input (2-D), ie GreyScale.

**Comment by gkrishnan724** [comment]
I'm taking this up ;)

**Comment by rahulkrishnan98** [comment]
It would also be pretty neat if you can generate both images from shifted as well noisy into different folders named the same.
